-- DDL generated by Postico 1.5.17
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE funds (
    code text PRIMARY KEY,
    name text NOT NULL,
    document text,
    quota_amount integer
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX untitled_table_pkey ON funds(code text_ops);
