-- DDL generated by Postico 1.5.17
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE historical_data (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    code text NOT NULL REFERENCES funds(code),
    p_vp numeric(15,5),
    dy numeric,
    last_price numeric(15,5) NOT NULL,
    date date NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX historical_data_pkey ON historical_data(id uuid_ops);
CREATE UNIQUE INDEX historical_data_code_date_idx ON historical_data(code text_ops,date date_ops);
