-- DDL generated by Postico 1.5.17
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE news (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    title text NOT NULL,
    link text,
    content text,
    date date,
    code text REFERENCES funds(code)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX news_pkey ON news(id uuid_ops);
